plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
future: true
repository: Noiro-0/Melian-Happy
author: Pemerintah Dusun Melian
permalink: /berita/:year/:month/:day/:title/
markdown: kramdown
url: https://melianhappy.vercel.app
defaults:
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
  - scope:
      path: _potensi
      type: potensi
    values:
      layout: potensi
twitter:
  username: dusunmelian
collections:
  potensi:
    output: true
    permalink: /potensi/:path/
title: Dusun Melian
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
locale: id_ID
description: Website Resmi Dusun Melian, Desa Candi, Kecamatan Pringkuku,
  Kabupaten Pacitan — Informasi, Berita, dan Potensi Dusun
dusun:
  kabupaten: Pacitan
  provinsi: Jawa Timur
  nama: Dusun Melian
  alamat: Dusun Melian, Desa Candi, Kec. Pringkuku, Kab. Pacitan, Jawa Timur
  desa: Candi
  whatsapp: "+6285335033114"
  kecamatan: Pringkuku
  kepala_dusun: Bapak Gangsar  Ipung H.C
  email: dusunmelianhappy@gmail.com
baseurl: ""
